# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{integrity-prowl}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Benny Wong"]
  s.date = %q{2009-09-27}
  s.description = %q{Sends a notification from Integrity to Prowl after each build}
  s.email = %q{benny@bwong.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "integrity-prowl.gemspec",
     "lib/integrity/notifier/config.haml",
     "lib/integrity/notifier/prowl.rb",
     "test/dict",
     "test/integrity_prowl_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/bdotdub/integrity-prowl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{integrity}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Prowl notifier for the Integrity continuous integration server}
  s.test_files = [
    "test/integrity_prowl_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<integrity>, [">= 0"])
      s.add_runtime_dependency(%q<prowl>, [">= 0"])
    else
      s.add_dependency(%q<integrity>, [">= 0"])
      s.add_dependency(%q<prowl>, [">= 0"])
    end
  else
    s.add_dependency(%q<integrity>, [">= 0"])
    s.add_dependency(%q<prowl>, [">= 0"])
  end
end
